from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT_DIR, "src")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

from knapsack_experiment.experiment import run_algorithm_experiment
from knapsack_experiment.io_utils import summarize_records, write_csv, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run one knapsack algorithm on the merged HotpotQA dataset."
    )
    parser.add_argument(
        "--dataset-path",
        required=True,
        help="Path to merged dataset JSONL generated by build_merged_dataset.py.",
    )
    parser.add_argument(
        "--algorithm",
        required=True,
        choices=["bruteforce", "exact_dp", "greedy_ratio", "greedy_refine"],
        help="Algorithm to run.",
    )
    parser.add_argument(
        "--budgets",
        type=int,
        nargs="+",
        default=[2000, 4000, 8000],
        help="Token budgets (raw token units).",
    )
    parser.add_argument(
        "--utility-method",
        choices=["lexical", "semantic", "hybrid"],
        default="lexical",
        help="Utility score method.",
    )
    parser.add_argument(
        "--utility-alpha",
        type=float,
        default=0.7,
        help="Hybrid: semantic weight.",
    )
    parser.add_argument(
        "--utility-beta",
        type=float,
        default=0.3,
        help="Hybrid: lexical weight.",
    )
    parser.add_argument(
        "--semantic-model-name",
        default="sentence-transformers/all-MiniLM-L6-v2",
        help="Sentence transformer model for semantic/hybrid utility.",
    )
    parser.add_argument(
        "--dp-cost-scale",
        type=int,
        default=1,
        help="Scale factor for exact DP costs/budgets. Use 1 for raw-token fair comparison.",
    )
    parser.add_argument(
        "--compute-optimality-gap",
        action="store_true",
        help="For non-DP runs, also compute exact DP utility per instance/budget.",
    )
    parser.add_argument(
        "--local-search-iterations",
        type=int,
        default=50,
        help="Max local-search iterations for greedy_refine.",
    )
    parser.add_argument(
        "--local-search-candidate-pool",
        type=int,
        default=300,
        help="Candidate pool size for greedy_refine swaps.",
    )
    parser.add_argument(
        "--max-instances",
        type=int,
        default=None,
        help="Optional cap for quick debugging.",
    )
    parser.add_argument(
        "--results-dir",
        default="results",
        help="Root directory for per-algorithm result files.",
    )
    parser.add_argument(
        "--run-name",
        default=None,
        help="Optional name for this run directory.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    run_name = args.run_name or timestamp
    out_dir = os.path.join(args.results_dir, args.algorithm, run_name)
    os.makedirs(out_dir, exist_ok=True)

    records, run_meta = run_algorithm_experiment(
        merged_dataset_path=args.dataset_path,
        algorithm=args.algorithm,
        budgets=args.budgets,
        utility_method=args.utility_method,
        utility_alpha=args.utility_alpha,
        utility_beta=args.utility_beta,
        semantic_model_name=args.semantic_model_name,
        dp_cost_scale=args.dp_cost_scale,
        max_instances=args.max_instances,
        compute_optimality_gap=args.compute_optimality_gap,
        local_search_iterations=args.local_search_iterations,
        local_search_candidate_pool=args.local_search_candidate_pool,
    )
    summary = summarize_records(records)

    detail_path = os.path.join(out_dir, "details.csv")
    summary_path = os.path.join(out_dir, "summary.csv")
    config_path = os.path.join(out_dir, "run_config.json")

    write_csv(detail_path, records)
    write_csv(summary_path, summary)
    write_json(config_path, run_meta)

    print(f"Algorithm run complete: {args.algorithm}")
    print(f"Instances processed: {run_meta['num_instances']}")
    print(f"Detail results: {detail_path}")
    print(f"Summary results: {summary_path}")
    print(f"Run config: {config_path}")


if __name__ == "__main__":
    main()
